import Image from "next/image"

import { cn } from "@/lib/utils"

/*
 * The DailyBread wordmark — the app's name IS the logo for now (explicit
 * direction). Served as WebP from `public/brand/`, rendered from the same
 * type this component used to set live: Playfair Display 700, tracking
 * -0.03em, "Daily" in --foreground and "Bread" in --primary-text.
 *
 * Two files, because the colours are the THEME's: the light file carries
 * #121417 / #ac5107 (brand-700, 4.9:1 on the page), the dark file #fafafb /
 * #febe90 (brand-300). They swap by CSS (`dark:`), never by JS, so the server
 * render is already right for either theme and nothing hydrates. `inverted`
 * is for a ground that is dark in BOTH themes, and always takes the dark file.
 *
 * `unoptimized`: an 8 KB WebP already at ~3× its display height gains nothing
 * from the optimiser's round trip. Size it by HEIGHT (`h-*`); the width
 * follows the 463×96 ratio.
 *
 * To replace the logo: swap the two files (keep the names), or change
 * WORDMARK below if the ratio changes. Generated by a one-off script; see
 * CLAUDE.md → Brand.
 */
const WORDMARK = { width: 463, height: 96 } as const

export function Logo({
  className = "h-6 lg:h-7",
  tone = "default",
}: {
  /** Height classes — e.g. `h-5` in the mobile sheet. */
  className?: string
  tone?: "default" | "inverted"
}) {
  const common = {
    alt: "DailyBread",
    width: WORDMARK.width,
    height: WORDMARK.height,
    unoptimized: true,
    // Default lazy loading, on purpose: the file hidden by the current theme
    // is `display: none` and is then never fetched, while the visible one is
    // already in the viewport and loads at once.
  }

  if (tone === "inverted") {
    return <Image src="/brand/dailybread-wordmark-dark.webp" {...common} className={cn("w-auto", className)} />
  }

  return (
    <>
      <Image src="/brand/dailybread-wordmark.webp" {...common} className={cn("w-auto dark:hidden", className)} />
      <Image src="/brand/dailybread-wordmark-dark.webp" {...common} className={cn("hidden w-auto dark:block", className)} />
    </>
  )
}
