import { prisma } from "@repo/db"
import type { AdminScopeContext } from "@repo/types/backend"
import { OTHER_REASON_CODE } from "@repo/types/enums"
import { ApiError } from "@/errors/ApiError"
import { assertReasonReach, reasonCodeFromLabel, firstFreeReasonCode } from "../lib/reasons/reason-choice"
import { logger } from "@/lib/pino/logger"
import { auditService } from "@/services/audit"

const serviceLog = logger.child({ module: "admin-action-reason-service" })

export { assertReasonReach } from "../lib/reasons/reason-choice"

export async function listActionReasons(filters: { appliesTo?: string; countryId?: string; activeOnly?: boolean }) {
  return prisma.adminActionReason.findMany({
    where: {
      ...(filters.appliesTo ? { appliesTo: { has: filters.appliesTo } } : {}),
      // countryId filter intentionally includes BOTH the country-specific
      // row (if any) and every global row — this is a listing endpoint,
      // not the single-reason resolver (see admin.vendor.service.ts's
      // resolveActionReason for the actual "pick one" resolution logic).
      ...(filters.countryId ? { OR: [{ countryId: filters.countryId }, { countryId: null }] } : {}),
      ...(filters.activeOnly ? { isActive: true } : {}),
    },
    orderBy: [{ countryId: "asc" }, { label: "asc" }],
  })
}

export async function getActionReason(id: string) {
  const reason = await prisma.adminActionReason.findUnique({ where: { id } })
  if (!reason) throw new ApiError(404, "Reason not found", "NOT_FOUND")
  return reason
}

/*
 * The code is SYSTEM-generated (reasonCodeFromLabel + firstFreeReasonCode) and
 * never edited. The ONE time a caller names a code is a COUNTRY VERSION of an
 * existing platform reason: it must reuse that reason's code, because sharing
 * the code is what makes it replace the platform one in that country. Any
 * other supplied code is refused, not silently replaced.
 */
export async function createActionReason(
  input: {
    code?: string
    label: string
    description?: string
    appliesTo: string[]
    countryId?: string
  },
  actorId: string,
  scope  : AdminScopeContext,
) {
  const supplied = input.code?.trim() || null
  if (supplied && supplied.toUpperCase() === OTHER_REASON_CODE) {
    throw new ApiError(400, `"${OTHER_REASON_CODE}" is reserved for the exception path`, "RESERVED_REASON_CODE")
  }
  assertReasonReach(scope, input.countryId ?? null)
  if (input.countryId) {
    const country = await prisma.country.findUnique({ where: { id: input.countryId }, select: { id: true } })
    if (!country) throw new ApiError(404, "Country not found", "NOT_FOUND")
  }

  let code: string
  if (supplied) {
    const platform = input.countryId
      ? await prisma.adminActionReason.findFirst({ where: { code: supplied, countryId: null }, select: { id: true } })
      : null
    if (!platform) {
      throw new ApiError(
        400,
        "Reason codes are generated by the system. Only a country version names a code: the platform reason it replaces.",
        "CODE_IS_SYSTEM_GENERATED",
      )
    }
    const duplicate = await prisma.adminActionReason.findFirst({
      where: { code: supplied, countryId: input.countryId! }, select: { id: true },
    })
    if (duplicate) {
      throw new ApiError(409, "This country already has its own version of that reason", "DUPLICATE_REASON")
    }
    code = supplied
  } else {
    const base  = reasonCodeFromLabel(input.label)
    const taken = await prisma.adminActionReason.findMany({ where: { code: { startsWith: base } }, select: { code: true } })
    code = firstFreeReasonCode(base, new Set(taken.map((t) => t.code)))
  }

  const reason = await prisma.adminActionReason.create({
    data: {
      code,
      label      : input.label,
      description: input.description ?? null,
      appliesTo  : input.appliesTo,
      countryId  : input.countryId ?? null,
    },
  })

  serviceLog.info({ reasonId: reason.id, actorId }, "Action reason created")
  auditService.log({
    adminUserId: actorId,
    action     : "admin_action_reason.created",
    entityType : "AdminActionReason",
    entityId   : reason.id,
    changes    : { after: { code: reason.code, countryId: reason.countryId } },
  })

  return reason
}

export async function updateActionReason(
  id: string,
  input: { label?: string; description?: string; appliesTo?: string[]; isActive?: boolean },
  actorId: string,
  scope  : AdminScopeContext,
) {
  const existing = await prisma.adminActionReason.findUnique({ where: { id } })
  if (!existing) throw new ApiError(404, "Reason not found", "NOT_FOUND")
  assertReasonReach(scope, existing.countryId)

  const updated = await prisma.adminActionReason.update({
    where: { id },
    data : {
      ...(input.label != null ? { label: input.label } : {}),
      ...(input.description != null ? { description: input.description } : {}),
      ...(input.appliesTo != null ? { appliesTo: input.appliesTo } : {}),
      ...(input.isActive != null ? { isActive: input.isActive } : {}),
    },
  })

  serviceLog.info({ reasonId: id, actorId }, "Action reason updated")
  auditService.log({
    adminUserId: actorId,
    action     : "admin_action_reason.updated",
    entityType : "AdminActionReason",
    entityId   : id,
    changes    : {
      before: { label: existing.label, description: existing.description, appliesTo: existing.appliesTo, isActive: existing.isActive },
      after : { label: updated.label, description: updated.description, appliesTo: updated.appliesTo, isActive: updated.isActive },
    },
  })

  return updated
}
